# Generated by Django 5.2.5 on 2025-10-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_voter_id",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("addr_street_number", models.CharField(blank=True, max_length=10)),
                ("addr_street_name", models.CharField(blank=True, max_length=120)),
                ("addr_apt_number", models.CharField(blank=True, max_length=20)),
                ("addr_zipcode", models.CharField(blank=True, max_length=10)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("date_of_registration", models.DateField(blank=True, null=True)),
                ("party", models.CharField(blank=True, max_length=2)),
                ("precinct", models.CharField(blank=True, max_length=10)),
                ("v20state", models.BooleanField(default=False)),
                ("v21town", models.BooleanField(default=False)),
                ("v21primary", models.BooleanField(default=False)),
                ("v22general", models.BooleanField(default=False)),
                ("v23town", models.BooleanField(default=False)),
                ("voter_score", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="voter_analy_last_na_81258d_idx",
                    ),
                    models.Index(
                        fields=["precinct"], name="voter_analy_precinc_344ac7_idx"
                    ),
                    models.Index(
                        fields=["voter_score"], name="voter_analy_voter_s_72bded_idx"
                    ),
                ],
            },
        ),
    ]
