# Generated by Django 5.2.5 on 2025-10-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="voter",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="voter",
            name="voter_analy_precinc_344ac7_idx",
        ),
        migrations.RemoveIndex(
            model_name="voter",
            name="voter_analy_voter_s_72bded_idx",
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="party",
            new_name="party_affiliation",
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="addr_street_number",
            new_name="residential_zip",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="addr_apt_number",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="addr_street_name",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="addr_zipcode",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="file_voter_id",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="precinct",
        ),
        migrations.AddField(
            model_name="voter",
            name="precinct_number",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="voter",
            name="residential_apartment",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="voter",
            name="residential_street_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="voter",
            name="residential_street_number",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="voter",
            name="voter_id_number",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="first_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="voter",
            name="last_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="voter",
            name="voter_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="voter",
            index=models.Index(
                fields=["precinct_number"], name="voter_analy_precinc_ee6f11_idx"
            ),
        ),
    ]
