# Generated by Django 5.2.5 on 2025-10-31 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0002_alter_voter_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="voter",
            name="voter_analy_last_na_81258d_idx",
        ),
        migrations.RemoveIndex(
            model_name="voter",
            name="voter_analy_precinc_ee6f11_idx",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="residential_apartment",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="residential_street_name",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="residential_street_number",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="residential_zip",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="voter_id_number",
        ),
        migrations.AddField(
            model_name="voter",
            name="apartment_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="voter",
            name="street_name",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voter",
            name="street_number",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voter",
            name="zip_code",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="voter",
            name="date_of_birth",
            field=models.DateField(default=datetime.date(1900, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="voter",
            name="date_of_registration",
            field=models.DateField(default=datetime.date(1900, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="voter",
            name="first_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="last_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="party_affiliation",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="voter",
            name="precinct_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v20state",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21primary",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21town",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v22general",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v23town",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="voter_score",
            field=models.IntegerField(),
        ),
    ]
