# Generated by Django 5.2.5 on 2025-10-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "voter_analytics",
            "0003_remove_voter_voter_analy_last_na_81258d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="apartment_number",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="voter",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="date_of_registration",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="first_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="voter",
            name="last_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="voter",
            name="party_affiliation",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AlterField(
            model_name="voter",
            name="precinct_number",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="voter",
            name="street_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="voter",
            name="street_number",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v20state",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21town",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v22general",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v23town",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="voter",
            name="voter_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="voter",
            name="zip_code",
            field=models.TextField(blank=True, default=""),
        ),
    ]
