# Generated by Django 5.2.5 on 2025-10-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0004_alter_voter_apartment_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="apartment_number",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="first_name",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="last_name",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="party_affiliation",
            field=models.CharField(blank=True, default="", max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="precinct_number",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="street_name",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="street_number",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="zip_code",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
