# Generated by Django 5.2.5 on 2025-10-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0003_post_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="image_url",
        ),
        migrations.AddField(
            model_name="photo",
            name="image_file",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
