# Generated by Django 5.2.5 on 2025-10-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0004_remove_photo_image_url_photo_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
