# Generated by Django 5.2.5 on 2025-10-24 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0009_profile_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={},
        ),
        migrations.AlterModelOptions(
            name="like",
            options={},
        ),
        migrations.RenameField(
            model_name="follow",
            old_name="timestamp",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="like",
            old_name="timestamp",
            new_name="created",
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="follow",
            name="followed",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="mini_insta.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="follow",
            name="follower",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to="mini_insta.profile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="mini_insta.post",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="mini_insta.profile",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("follower", "followed"), name="unique_follow"
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.CheckConstraint(
                condition=models.Q(("follower", models.F("followed")), _negated=True),
                name="no_self_follow",
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("profile", "post"), name="unique_like"
            ),
        ),
        migrations.RemoveField(
            model_name="follow",
            name="follower_profile",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="profile",
        ),
    ]
