# File: project/admin.py
# Author: Louise Lee, llouise@bu.edu, 11/24/2025
# Description: What models we give admin access to
# Admin configuration for digital desk models

# Give access to django admin to see models
from django.contrib import admin
from .models import (
    Profile,
    TimerRecord,
    WaterLog,
    DiaryEntry,
    PhotoItem,
    StickyNote,
    DeskBuddy,
)


@admin.register(Profile)
class ProfileAdmin(admin.ModelAdmin):
    list_display = [
        "user",
        "display_name",
        "created_at",
        "get_weekly_focus",
        "get_weekly_tasks",
    ]
    list_filter = ["created_at"]
    search_fields = ["user__username", "display_name"]
    date_hierarchy = "created_at"

    def get_weekly_focus(self, obj):
        return f"{obj.get_weekly_focus_minutes()} min"

    get_weekly_focus.short_description = "Weekly Focus"

    def get_weekly_tasks(self, obj):
        return obj.get_weekly_tasks_completed()

    get_weekly_tasks.short_description = "Weekly Tasks"


@admin.register(TimerRecord)
class TimerRecordAdmin(admin.ModelAdmin):
    list_display = [
        "user",
        "label",
        "start_time",
        "status",
        "cycles_completed",
        "planned_cycles",
        "focus_duration_minutes",
    ]
    list_filter = ["user", "status", "start_time"]
    search_fields = ["label", "user__username"]
    date_hierarchy = "start_time"
    list_editable = ["status"]


@admin.register(WaterLog)
class WaterLogAdmin(admin.ModelAdmin):
    list_display = [
        "user",
        "date",
        "total_intake_ml",
        "daily_goal_ml",
        "get_percentage_display",
    ]
    list_filter = ["user", "date"]
    search_fields = ["user__username"]
    date_hierarchy = "date"

    def get_percentage_display(self, obj):
        return f"{obj.get_percentage_complete():.1f}%"

    get_percentage_display.short_description = "Progress"


@admin.register(DiaryEntry)
class DiaryEntryAdmin(admin.ModelAdmin):
    list_display = ["user", "title", "date", "created_at"]
    list_filter = ["user", "date"]
    search_fields = ["title", "content", "user__username"]
    date_hierarchy = "date"


@admin.register(PhotoItem)
class PhotoItemAdmin(admin.ModelAdmin):
    list_display = ["user", "caption", "date_added"]
    list_filter = ["user", "date_added"]
    search_fields = ["caption", "user__username"]
    date_hierarchy = "date_added"


@admin.register(StickyNote)
class StickyNoteAdmin(admin.ModelAdmin):
    list_display = ["title", "user", "color", "is_completed", "due_date", "created_at"]
    list_filter = ["user", "color", "is_completed", "due_date"]
    search_fields = ["title", "content", "user__username"]
    date_hierarchy = "created_at"
    list_editable = ["is_completed"]


@admin.register(DeskBuddy)
class DeskBuddyAdmin(admin.ModelAdmin):
    list_display = ["user", "message_preview", "is_read", "created_at"]
    list_filter = ["user", "is_read", "created_at"]
    search_fields = ["affirmation", "user__username"]
    date_hierarchy = "created_at"
    readonly_fields = ["user", "affirmation", "created_at"]

    def message_preview(self, obj):
        return (
            obj.affirmation[:60] + "..."
            if len(obj.affirmation) > 60
            else obj.affirmation
        )

    message_preview.short_description = "Message"

    def has_add_permission(self, request):
        # Users cannot manually add messages - they're generated by the app
        return False
