# Generated by Django 5.2.5 on 2025-11-25 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Short title for your entry", max_length=200
                    ),
                ),
                ("content", models.TextField(help_text="Write your thoughts here")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Diary Entries",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PhotoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="desk_photos/")),
                (
                    "caption",
                    models.CharField(
                        blank=True, help_text="Optional caption", max_length=200
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_added"],
            },
        ),
        migrations.CreateModel(
            name="StickyNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Short title", max_length=100)),
                ("content", models.TextField(help_text="Note content")),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("yellow", "Yellow"),
                            ("pink", "Pink"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("purple", "Purple"),
                        ],
                        default="yellow",
                        max_length=20,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Optional reminder date", null=True
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sticky_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["is_completed", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeskBuddy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("sticky_reminder", "Sticky Note Reminder"),
                            ("water", "Water Reminder"),
                            ("encouragement", "Encouragement"),
                            ("break", "Break Reminder"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message_text", models.TextField(help_text="The message to display")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desk_buddy_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_sticky_note",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to sticky note if this is a reminder",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.stickynote",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Desk Buddy Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimerRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="What are you working on?", max_length=200
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "focus_duration_minutes",
                    models.IntegerField(default=25, help_text="Focus time per cycle"),
                ),
                (
                    "break_duration_minutes",
                    models.IntegerField(default=5, help_text="Break time per cycle"),
                ),
                (
                    "num_cycles",
                    models.IntegerField(
                        default=1, help_text="Number of completed cycles"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timer_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="WaterLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "total_intake_ml",
                    models.IntegerField(
                        default=0, help_text="Total water consumed (ml)"
                    ),
                ),
                (
                    "daily_goal_ml",
                    models.IntegerField(
                        default=2000, help_text="Daily water goal (ml)"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
