# Generated by Django 5.2.5 on 2025-11-25 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deskbuddy",
            name="message_text",
        ),
        migrations.RemoveField(
            model_name="deskbuddy",
            name="message_type",
        ),
        migrations.RemoveField(
            model_name="deskbuddy",
            name="related_sticky_note",
        ),
        migrations.RemoveField(
            model_name="timerrecord",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="timerrecord",
            name="num_cycles",
        ),
        migrations.AddField(
            model_name="deskbuddy",
            name="affirmation",
            field=models.TextField(
                default=django.utils.timezone.now, help_text="The affirmation message"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stickynote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="timerrecord",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timerrecord",
            name="cycles_completed",
            field=models.IntegerField(
                default=0, help_text="Number of cycles completed"
            ),
        ),
        migrations.AddField(
            model_name="timerrecord",
            name="planned_cycles",
            field=models.IntegerField(default=1, help_text="Number of cycles planned"),
        ),
        migrations.AddField(
            model_name="timerrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stickynote",
            name="content",
            field=models.TextField(
                blank=True, help_text="Optional note content", null=True
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=100)),
                (
                    "bio",
                    models.TextField(blank=True, help_text="A little about yourself"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("default_focus_minutes", models.IntegerField(default=25)),
                ("default_break_minutes", models.IntegerField(default=5)),
                ("daily_water_goal_ml", models.IntegerField(default=2000)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desk_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
