# Generated by Django 5.2.5 on 2025-12-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_remove_deskbuddy_message_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoitem",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this photo will be shown on your desk.",
            ),
        ),
    ]
