# Generated by Django 5.2.5 on 2025-12-09 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_photoitem_is_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stickynote",
            name="color",
        ),
        migrations.AlterField(
            model_name="photoitem",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="waterlog",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
